### ISSUE TITLE
Support for Fabric Language Kotlin 1.4.0

### ISSUE THREAD

**Issue by ghost** [Juuxel/Adorn#102]
The new versions of Astromine require Fabric Language Kotline 1.4.0 to be installed, as can be seen in https://github.com/Mixinors/Astromine/issues/255.
However, installing Fabric Language Kotline 1.4.0 manually while having the latest Adorn release installed crashes the game at startup:

<details>
  <summary>Crash log</summary>

```
[13:29:55] [main/INFO]: RebornCore found, loading compatibility for fluids.
[13:29:55] [main/INFO]: [expandedstorage] New config keys found, saved merged config.
---- Minecraft Crash Report ----
// Oops.

Time: 9/6/20, 1:29 PM
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'adorn'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at kotlin.reflect.jvm.internal.impl.types.ErrorUtils$1.getBuiltIns(ErrorUtils.java:139)
	at kotlin.reflect.jvm.internal.impl.resolve.descriptorUtil.DescriptorUtilsKt.getBuiltIns(DescriptorUtils.kt:167)
	at kotlin.reflect.jvm.internal.impl.descriptors.impl.TypeParameterDescriptorImpl.createWithDefaultBound(TypeParameterDescriptorImpl.java:56)
	at kotlin.reflect.jvm.internal.impl.builtins.SuspendFunctionTypesKt.<clinit>(suspendFunctionTypes.kt:33)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.createSuspendView(LazyJavaClassMemberScope.kt:176)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.doesOverrideSuspendFunction(LazyJavaClassMemberScope.kt:167)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.isVisibleAsFunctionInCurrentClass(LazyJavaClassMemberScope.kt:121)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredFunctions(LazyJavaClassMemberScope.kt:276)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:120)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope$functions$1.invoke(LazyJavaScope.kt:58)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:602)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaScope.getContributedFunctions(LazyJavaScope.kt:276)
	at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedFunctions(LazyJavaClassMemberScope.kt:751)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.computeNonDeclaredFunctions(DeserializedClassDescriptor.kt:252)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeFunctions(DeserializedMemberScope.kt:108)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeFunctions(DeserializedMemberScope.kt:40)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(DeserializedMemberScope.kt:66)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$functions$1.invoke(DeserializedMemberScope.kt:40)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:527)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:602)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedFunctions(DeserializedMemberScope.kt:145)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedFunctions(DeserializedClassDescriptor.kt:241)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.addFunctionsAndProperties(DeserializedMemberScope.kt:227)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(DeserializedMemberScope.kt:187)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:227)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(DeserializedClassDescriptor.kt:220)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:370)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:489)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(DeserializedClassDescriptor.kt:237)
	at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(ResolutionScope.kt:52)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(KDeclarationContainerImpl.kt:57)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:161)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:46)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:170)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:46)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt)
	at kotlin.reflect.full.KClasses.getMemberFunctions(KClasses.kt:104)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.java:65)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 21 more
Caused by: java.lang.IllegalStateException: Resource not found in classpath: kotlin/kotlin.kotlin_builtins
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createBuiltInPackageFragmentProvider(BuiltInsLoaderImpl.kt:59)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl.createPackageFragmentProvider(BuiltInsLoaderImpl.kt:35)
	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:125)
	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:24)
	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<init>(DefaultBuiltIns.kt:21)
	at kotlin.reflect.jvm.internal.impl.builtins.DefaultBuiltIns.<clinit>(DefaultBuiltIns.kt:31)
	... 68 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 5.9.0-rc2
	Java Version: 14.0.2-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1943957504 bytes (1853 MB) / 2902458368 bytes (2768 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1024m -Xmx8192m
	Fabric Mods: 
		adorn: Adorn 1.11.0+1.16.2
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.7
		astromine: Astromine 1.9.2+fabric-1.16.2
		astromine-core: Astromine: Core 1.9.2+fabric-1.16.2
		astromine-discoveries: Astromine: Discoveries 1.9.2+fabric-1.16.2
		astromine-foundations: Astromine: Foundations 1.9.2+fabric-1.16.2
		astromine-technologies: Astromine: Technologies 1.9.2+fabric-1.16.2
		astromine-transportations: Astromine: Transportations 1.9.2+fabric-1.16.2
		authme: Auth Me 1.3.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bettergraves: Better Graves 0.4.1
		blade: Blade 1.0.1
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.0.5
		canvas: Canvas Renderer 1.0.913
		cardinal-components-base: Cardinal Components API (base) 2.5.4
		cardinal-components-block: Cardinal Components API (blocks) 2.5.4
		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.4
		cardinal-components-entity: Cardinal Components API (entities) 2.5.4
		cardinal-components-item: Cardinal Components API (items) 2.5.4
		cardinal-components-level: Cardinal Components API (world saves) 2.5.4
		cardinal-components-util: Cardinal Components API (utilities) 2.5.4
		cardinal-components-world: Cardinal Components API (worlds) 2.5.4
		chainmail: Chainmail 0.5.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.1
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.6
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.6
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.6
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.0
		expandedstorage: ExpandedStorage 5.6.26
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		fermion: Fermion 2.5.202
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fermion-orientation: Fermion Orientation 1.1.201
		fermion-varia: Fermion Varia 2.3.202
		fiber: fiber 0.23.0-1
		frex: FREX 3.3.137
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		improved-stations: Improved Stations 2.0.3
		jankson: Jankson 3.0.1+j1.2.0
		joml-mod: JOML Mod 1.4.20
		json-model-extensions: JSON Model Extensions 1.15.124
		justmap: Just Map 1.2.9
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.2-pre.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2-pre.1
		libblockattributes_items: LibBlockAttributes (Items) 0.8.2-pre.1
		libcd: LibCapableData 2.5.0+1.16.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.1
		linkedstorage: Linked Storage 1.3.7-1.16
		lithium: Lithium 0.5.2
		magna: Magna 1.4.0-1.16.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-40-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		reborncore: Reborn Core 4.4.1+build.69
		roughlyenoughitems: Roughly Enough Items 5.2.10
		roughlyenoughitems-api: REI (API) 5.2.10
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.10
		roughlyenoughitems-runtime: REI (Runtime) 5.2.10
		shapes: Shapes 2.0.0+build.10
		special-circumstances: Special Circumstances 1.7.202
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.5.2+build.110
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		waila: Hwyla 1.9.22
		wrenchable: Wrenchable 1.0.0+1.16.1
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/pbb/.multimc/instances/PBBTechPack 1.16.2 v1.1.2/.minecraft/crash-reports/crash-2020-09-06_13.29.58-client.txt
Process exited with code 255.

```
  
</details>

**Comment by Juuxel** [comment]
You need to update Fabric Loader (this was fixed by FabricMC/fabric-loader#305).
