### ISSUE TITLE
Adorn version 1.1.1 crashes on startup (using Fabric API 0.3.0 build 176 and Fabric Language Kotlin 1.3.31+build.4) 

### ISSUE THREAD

**Issue by TheLoanShark** [Juuxel/Adorn#19]
Time: 6/12/19 1:08 PM
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint main!
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:151)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:151)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:186)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3886725072 bytes (3706 MB) / 4294967296 bytes (4096 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.1.1+1.14.2
		cotton: Cotton 0.7.3+1.14.2-SNAPSHOT
		fabric: Fabric API 0.3.0-pre+build.157a
		fabric-api-base: fabric-api-base 0.1.0+f1618918
		fabric-commands-v0: fabric-commands-v0 0.1.0+f1618918
		fabric-containers-v0: fabric-containers-v0 0.1.0+f1618918
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+f1618918
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+f1618918
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+9232ac87
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f1618918
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+f1618918
		fabric-language-kotlin: Fabric Language Kotlin 1.3.31+build.4
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+f1618918
		fabric-models-v0: fabric-models-v0 0.1.0+f1618918
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.0+f1618918
		fabric-networking-v0: fabric-networking-v0 0.1.1+57f0d19c
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.0+9232ac87
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.1.0+f1618918
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+f1618918
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.0+f1618918
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+f1618918
		fabric-textures-v0: fabric-textures-v0 0.1.0+f1618918
		fabricloader: Fabric Loader 0.4.8+build.155
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.1
		polyester: Polyester 0.3.0+1.14.1
		towelette: Towelette 1.7.0
	Launched Version: fabric-loader-0.4.8+build.155-1.14.2+build.7
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by Juuxel** [comment]
This should be fixed now.
