### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TimGoll** [Juuxel/Adorn#2]
Adorn version 0.1.1 crashes with Minecraft 1.14, loader 127. There is no crash report, however this message is in the console

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:146)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: adorn requires {fabric @ [>=0.2.0 && >=0.3.0-pre]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:477)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:144)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 12 more
```

**Comment by Juuxel** [comment]
Update to loader build 139. The changes in 0.1.1 depend on FabricMC/fabric-loader@200e06b.

**Comment by TimGoll** [comment]
Oh okay. Then I have to wait until the other mods are updates. Thanks :)

**Comment by Juuxel** [comment]
Note: if support for Fabric API 0.3.0-pre is not needed, you can just use Adorn 0.1.0.

**Comment by TimGoll** [comment]
Okay. I'm using now loader 143 in combination with adorn 0.1.3. It still crashes.

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: adorn requires {fabric-language-kotlin @ [>=1.3.30]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:477)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 12 more
```

**Comment by TimGoll** [comment]
Okay. I fixed it, my version of kotlin was too old.
