### ISSUE TITLE
Crash Error

### ISSUE THREAD

**Issue by KaspianDev** [Juuxel/Adorn#251]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.3.1
- Minecraft: 1.18.1
- Fabric Loader: 0.10.2
- Fabric API: 0.46.4

```
15:43:47] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adorn'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.2.jar:?]
        at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.2.jar:?]
        Suppressed: java.lang.IllegalStateException: java.io.IOException: BYG config found at: "./config/byg/overworld-biomes.json" could not be read. The fastest solution is to rename this failed file and let a new file generate from BYG and replace the fields in the new file with the broken file's fields.
                at potionstudios.byg.config.json.OverworldBiomeConfig.readConfig(OverworldBiomeConfig.java:62) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                at potionstudios.byg.config.json.OverworldBiomeConfig.getConfig(OverworldBiomeConfig.java:34) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                at potionstudios.byg.entry.BYGTerraBlenderEntry.onTerraBlenderInitialized(BYGTerraBlenderEntry.java:35) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                at terrablender.core.TerraBlenderFabric.lambda$onInitialize$1(TerraBlenderFabric.java:46) ~[TerraBlender-fabric-1.18.1-1.1.0.77.jar:?]
                at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
                at terrablender.core.TerraBlenderFabric.onInitialize(TerraBlenderFabric.java:41) ~[TerraBlender-fabric-1.18.1-1.1.0.77.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
                at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.2.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.2.jar:?]
                at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.2.jar:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.2.jar:?]
        Caused by: java.io.IOException: BYG config found at: "./config/byg/overworld-biomes.json" could not be read. The fastest solution is to rename this failed file and let a new file generate from BYG and replace the fields in the new file with the broken file's fields.
                at potionstudios.byg.util.BYGUtil.configFileFailureException(BYGUtil.java:97) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                at potionstudios.byg.config.json.OverworldBiomeConfig.lambda$readConfig$3(OverworldBiomeConfig.java:60) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
                at potionstudios.byg.config.json.OverworldBiomeConfig.readConfig(OverworldBiomeConfig.java:60) ~[Oh+The+Biomes+You'll+Go-fabric-1.18.1-1.3.5.13.jar:?]
                ... 21 more
Caused by: java.lang.ExceptionInInitializerError
        at juuxel.adorn.Adorn.onInitialize(Adorn.kt:32) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
        ... 15 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3767()" because the return value of "uk.debb.vanilla_disable.gamerules.RegisterGamerules.getServer()" is null
        at net.minecraft.class_2248.handler$ecc000$cancelFriction(class_2248.java:4651) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_9499(class_2248.java) ~[server-intermediary.jar:?]
        at juuxel.adorn.util.ExtensionsKt.copySettingsSafely(ExtensionsKt.java:53) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.api.block.BlockVariant$Companion$variant$$inlined$variant$1.createSettings(BlockVariant.java:92) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.SofaBlock.<init>(SofaBlock.java:42) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.platform.BlockFactory$DefaultImpls.createSofa(BlockFactory.java:7) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.platform.BlockFactory$Default.createSofa(BlockFactory.java:9) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.AdornBlocks$SOFAS$2$1.invoke(AdornBlocks.java:29) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.AdornBlocks$SOFAS$2$1.invoke(AdornBlocks.java:29) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.platform.fabric.RegistrarImpl.register(RegistrarImpl.kt:11) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.lib.RegistryHelper.registerBlockWithoutItem(RegistryHelper.java:51) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.lib.RegistryHelper.access$registerBlockWithoutItem(RegistryHelper.java:16) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:84) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.lib.RegistryHelper.registerBlock$default(RegistryHelper.java:27) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.AdornBlocks$SOFAS$2.invoke(AdornBlocks.java:29) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.AdornBlocks$SOFAS$2.invoke(AdornBlocks.java:26) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.util.ExtensionsKt.associateLazily(ExtensionsKt.java:86) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.block.AdornBlocks.<clinit>(AdornBlocks.java:26) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at juuxel.adorn.Adorn.onInitialize(Adorn.kt:32) ~[Adorn-3.3.1+1.18.1-fabric.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
        ... 15 more
```

mod list
```
[15:43:31] [main/INFO]: Loading 172 mods:
	- additionaladditions 3.0.1
	- adorn 3.3.1+1.18.1
	- advancednetherite 1.4.1-1.18.2
	- alloy_forgery 2.0.9+1.18
	- alternatecurrent 1.1.0
	- apoli 2.2.2 via origins
	- appleskin 2.3.0+mc1.18.1
	- architectury 3.7.20
	- artifacts 6.0.0+fabric
	- artifality 0.5.5
	- attributefix 13.0.5
	- backslot 1.2.5
	- blossom 1.18.1-1.0.3
	- blue_endless_jankson 1.2.1 via jankson
	- bno 1.18.1-7.1.2-Fabric
	- botania 1.18.1-429-FABRIC
	- byg 1.3.5.13
	- c2me 0.2.0+alpha.6.55
	- caffeineconfig 1.0.0 via vanilla_disable
	- calio 1.4.2 via apoli
	- campanion 3.0.2
	- cardinal-components-base 4.0.0 via trinkets
	- cardinal-components-entity 4.0.0 via trinkets
	- carpet 1.4.57
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- com_electronwill_night-config_core 3.6.4 via servercore
	- com_electronwill_night-config_toml 3.6.4 via servercore
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_github_wearblackallday_javautils bd58640372 via dimthread
	- com_ishland_c2me_libs_ 0.2.0+alpha.6.55 via c2me
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- cosmetic-armor 1.2.1
	- crowdin-translate 1.4+1.18 via fabricshieldlib
	- customportalapi 0.0.1-beta49-1.18 via moreweaponry
	- damagetilt 1.18-fabric-0.1.2
	- decorative_blocks 2.0.4
	- dimthread 1.2.6
	- drinkbeer 3.0.2
	- emerald_tools 1.3.37
	- emotecraft 2.1
	- enchant_giver 1.1.0 via mythicmetals
	- expandability 5.0.0 via artifacts
	- extraorigins 1.18-9
	- fabric 0.46.4+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric
	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via spark
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric
	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric
	- fabricloader 0.13.2
	- fabricshieldlib 1.5.1-pre1-1.18
	- feature_nbt_deadlock_be_gone 1.0.1+1.18.1
	- ferritecore 4.1.2
	- fiber 0.23.0-2 via patchouli
	- friendsandfoes 1.2.5
	- geckolib3 3.0.33
	- genesis 1.18.1-1.0.0
	- goblintraders 1.5
	- guardvillagers 1.0.7
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- inventory_backpack 0.2.4
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- javax_servlet_javax_servlet-api 3.1.0 via mtr
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- krypton 0.1.6
	- ksyxis 1.1
	- levelz 1.1.6
	- libgui 5.3.0+1.18 via levelz
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.8
	- mcwfences 1.0.4
	- medievalweapons 1.1.8
	- minecraft 1.18.1
	- minecraftmappings 1.18-1.0.0 via mtr
	- mm 2.3 via fabricshieldlib
	- morevillagers-fabric 3.1.1-SNAPSHOT
	- moreweaponry 1.15.43+1.18
	- mostructures 1.3.0-pre1+1.18
	- mtr 1.18.1-3.0.0-beta-8
	- mythic-mounts 1.18-5.0
	- mythicmetals 0.11.4
	- nbtcrafting 2.1.2+mc1.18.1
	- no_null_processors 2.0.1+1.18.1
	- omega-config 1.2.2-1.18.1 via friendsandfoes
	- org_eclipse_jetty_jetty-http 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-io 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-security 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-server 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-servlet 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-util 9.4.44.v20210927 via mtr
	- org_eclipse_jetty_jetty-util-ajax 9.4.44.v20210927 via mtr
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- origins 1.3.1
	- origins-classes 1.2.4
	- owo 0.5.2+1.18
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- patchouli 1.18.1-65-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- placeholder-api 1.1.3+1.17.1 via universal-graves
	- playerabilitylib 1.3.0 via apoli
	- polymer 0.2.0-beta.24+1.18.1 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-beta.24+1.18.1 via polymer
	- pugh_tools 1.1.17 via emerald_tools
	- reach-entity-attributes 2.1.1 via medievalweapons
	- recipecache 0.2.1-1.17.1
	- roughlyenoughitems 7.3.432
	- roughlyenoughresources 2.4.1
	- server_translations_api 1.4.8+1.18-pre1 via universal-graves
	- servercore 1.2.7-1.18.1
	- sgui 1.0.0-rc6+1.18-pre5 via universal-graves
	- spark 1.8.8
	- starlight 1.0.0+fabric.d0a3220
	- step-height-entity-attribute 1.0.0 via artifacts
	- terrablender 1.1.0.77
	- thonkutil-base 1.5.1+31ad4eb1c8 via goblintraders
	- thonkutil-capes-v1 1.2.2+befce073c8 via goblintraders
	- thonkutil-potions-v0 1.3.1+befce073c8 via goblintraders
	- thonkutil-trades-v1 1.1.8+d77526a2c8 via goblintraders
	- towers_of_the_wild_reworked 2.2.0
	- trinkets 3.2.0
	- twigs 1.1.2
	- universal-graves 2.0.0-rc.4+1.18.1
	- vanilla_disable 1.3.1
	- villager-hats 1.3.0
	- vmp 0.2.0+beta.3.8
	- waystones 2.4.1
	- wthit 4.5.4
	- xaerominimap 22.2.0.1
	- xaeroworldmap 1.20.3.1
```

**Comment by Juuxel** [comment]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3767()" because the return value of "uk.debb.vanilla_disable.gamerules.RegisterGamerules.getServer()" is null

This is a problem with vanilla_disable trying to query the server when block settings are accessed which is *very incorrect*
