### ISSUE TITLE
Crash on world start! :(

### ISSUE THREAD

**Issue by RetroAech** [Juuxel/Adorn#26]
https://paste.ee/p/yn0yn

**Comment by Juuxel** [comment]
- The crash seems to be caused by AnimalNet.
  ```
  java.lang.NullPointerException: Exception in server tick loop
  	at java.util.HashMap.putMapEntries(Unknown Source)
  	at java.util.HashMap.<init>(Unknown Source)
  	at me.marnic.animalnet.mechanics.ServerHandler.handleServerStarting(ServerHandler.java:44)
  	at net.minecraft.class_1132.handler$setup$zma001(class_1132.java:1041)
  ```
- You have outdated LibCD and LibGui, which can cause some issues with Adorn's guis and data loading. You can either update them or just disable them in MultiMC, as they're included in Adorn.
