### ISSUE TITLE
Issue Loading EMI Plugin

### ISSUE THREAD

**Issue by sylv256** [Juuxel/Adorn#295]
### Adorn version

3.7.0+1.19.2

### Minecraft version

1.19.2

### Mod loader

Quilt

### Mod loader version

0.18.1-beta.11 / 4.0.0-beta.20+0.66.0-1.19.2

### Describe the bug

The Adorn EMI plugin fails to load.
```
[22:15:11] [Thread-33/INFO]: [STDERR]: [emi] [emi] Exception loading plugin provided by adorn
[22:15:11] [Thread-33/INFO]: [STDERR]: java.lang.IllegalArgumentException: Fluid may not be flowing.
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:41)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:65)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at juuxel.adorn.compat.emi.ExtensionsKt.toEmiIngredient(Extensions.kt:14)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at juuxel.adorn.compat.emi.BrewingEmiRecipe.<init>(BrewingEmiRecipe.kt:41)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at juuxel.adorn.compat.emi.AdornEmiPlugin.register(AdornEmiPlugin.kt:33)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:99)
[22:15:11] [Thread-33/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:15:11] [Thread-33/INFO]: [STDERR]: [emi] java.lang.IllegalArgumentException: Fluid may not be flowing.
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:41)
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:65)
	at juuxel.adorn.compat.emi.ExtensionsKt.toEmiIngredient(Extensions.kt:14)
	at juuxel.adorn.compat.emi.BrewingEmiRecipe.<init>(BrewingEmiRecipe.kt:41)
	at juuxel.adorn.compat.emi.AdornEmiPlugin.register(AdornEmiPlugin.kt:33)
	at dev.emi.emi.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:99)
	at java.base
```

### To reproduce

1. Install QFAPI, EMI, and Adorn.
2. Run the game.

### Game logs

```text
https://mclo.gs/wc2FccS
```

### Additional context

I'm not sure if this causes any issues, but I'd assume so considering it throws an exception while trying to load the plugin..

**Comment by Juuxel** [comment]
I suspect this is a three-way incompat issue between Adorn, EMI and Milk Lib/mods providing `#c:milk`.

For the hot chocolate recipe, Adorn uses said tag if it's available:

https://github.com/Juuxel/Adorn/blob/1.19/fabric/src/main/resources/data/adorn/recipes/brewing/hot_chocolate_from_fluid.json

Naturally, it also tries to make a brewing recipe container for EMI so it can see this recipe. EMI's fluid ingredients are backed by a (Q)FAPI `FluidVariant`.

However, the tag includes a flowing milk fluid and FluidVariants cannot be created for flowing fluids => crash.

(not 100% sure this is correct since I'm on my phone)

**Comment by sylv256** [comment]
I'll do some more scientific testing tomorrow to confirm this.
