### ISSUE TITLE
Server Unable to Start with Enderscape 0.4.0

### ISSUE THREAD

**Issue by TeaJeep** [Juuxel/Adorn#296]
### Adorn version

3.7.0

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric 1.14.10

### Describe the bug

Using latest Adorn (3.7.0) and Enderscape(0.4.0) on a Fabric 1.14.10 server, the server fails to start with a "Failed to Start Minecaft Server:" Error

### To reproduce

Latest Fabric Server, Adorn, and Enderscape, running on a server.

### Game logs

```text
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adorn'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar:0.11.1]
Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.bunten.enderscape.config.Config
at net.bunten.enderscape.world.EnderscapeBiomes.getSkyBiomeHeight(EnderscapeBiomes.java:56) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.world.placed.FeaturesClass.(FeaturesClass.java:24) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.world.biomes.CelestialIslandsBiome.getBCLBiome(CelestialIslandsBiome.java:50) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.world.EnderscapeBiomes.register(EnderscapeBiomes.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.world.EnderscapeBiomes.(EnderscapeBiomes.java:63) ~[enderscape-0.4.0-1.19.2.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:495) ~[?:?]
at java.lang.Class.forName(Class.java:474) ~[?:?]
at com.google.common.reflect.Reflection.initialize(Reflection.java:66) ~[guava-31.0.1-jre.jar:?]
at net.bunten.enderscape.Enderscape.onInitialize(Enderscape.java:38) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.10.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.10.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Cannot load class net.bunten.enderscape.config.configs.DebugConfig in environment type SERVER [in thread "main"]
at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at net.bunten.enderscape.config.Config.(Config.java:23) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.registry.EnderscapeModifications.lambda$static$5(EnderscapeModifications.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.blocks.SoundTypeModification.applies(SoundTypeModification.java:32) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.minecraft.class_2248.handler$bfp000$getSoundType(class_2248.java:3678) ~[server-intermediary.jar:?]
at net.minecraft.class_2248.method_9573(class_2248.java) ~[server-intermediary.jar:?]
at net.minecraft.class_4970$class_4971.method_26231(class_4970.java:1053) ~[server-intermediary.jar:?]
at juuxel.adorn.util.ExtensionsKt.copySettingsSafely(ExtensionsKt.java:54) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.api.block.BlockVariant$Companion$variant$$inlined$variant$1.createSettings(BlockVariant.java:93) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.PostBlock.(PostBlock.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.END_STONE_BRICK_POST_delegate$lambda-80(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.platform.fabric.RegistrarImpl.register(RegistrarImpl.kt:11) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlockWithoutItem(RegistryHelper.java:44) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:29) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock$default(RegistryHelper.java:22) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.Adorn.onInitialize(Adorn.kt:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
... 9 more
Caused by: java.lang.ExceptionInInitializerError
at net.bunten.enderscape.registry.EnderscapeModifications.lambda$static$5(EnderscapeModifications.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.blocks.SoundTypeModification.applies(SoundTypeModification.java:32) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.minecraft.class_2248.handler$bfp000$getSoundType(class_2248.java:3678) ~[server-intermediary.jar:?]
at net.minecraft.class_2248.method_9573(class_2248.java) ~[server-intermediary.jar:?]
at net.minecraft.class_4970$class_4971.method_26231(class_4970.java:1053) ~[server-intermediary.jar:?]
at juuxel.adorn.util.ExtensionsKt.copySettingsSafely(ExtensionsKt.java:54) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.api.block.BlockVariant$Companion$variant$$inlined$variant$1.createSettings(BlockVariant.java:93) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.PostBlock.(PostBlock.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.END_STONE_BRICK_POST_delegate$lambda-80(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.platform.fabric.RegistrarImpl.register(RegistrarImpl.kt:11) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlockWithoutItem(RegistryHelper.java:44) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:29) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock$default(RegistryHelper.java:22) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.Adorn.onInitialize(Adorn.kt:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
... 8 more
Caused by: java.lang.RuntimeException: Cannot load class net.bunten.enderscape.config.configs.DebugConfig in environment type SERVER
at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.10.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.10.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at net.bunten.enderscape.config.Config.(Config.java:23) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.registry.EnderscapeModifications.lambda$static$5(EnderscapeModifications.java:47) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.bunten.enderscape.blocks.SoundTypeModification.applies(SoundTypeModification.java:32) ~[enderscape-0.4.0-1.19.2.jar:?]
at net.minecraft.class_2248.handler$bfp000$getSoundType(class_2248.java:3678) ~[server-intermediary.jar:?]
at net.minecraft.class_2248.method_9573(class_2248.java) ~[server-intermediary.jar:?]
at net.minecraft.class_4970$class_4971.method_26231(class_4970.java:1053) ~[server-intermediary.jar:?]
at juuxel.adorn.util.ExtensionsKt.copySettingsSafely(ExtensionsKt.java:54) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.api.block.BlockVariant$Companion$variant$$inlined$variant$1.createSettings(BlockVariant.java:93) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.PostBlock.(PostBlock.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.END_STONE_BRICK_POST_delegate$lambda-80(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.platform.fabric.RegistrarImpl.register(RegistrarImpl.kt:11) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlockWithoutItem(RegistryHelper.java:44) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:29) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:23) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.lib.RegistryHelper.registerBlock$default(RegistryHelper.java:22) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.block.AdornBlocks.(AdornBlocks.java:120) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at juuxel.adorn.Adorn.onInitialize(Adorn.kt:35) ~[Adorn-3.7.0+1.19.2-fabric.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.10.jar:?]
... 8 more
```

### Additional context

While I believe this is an issue with Enderscape, I might be wrong and wanted to make sure to post on both issue trackers. 

Here's the link to the issue tracker there! Apologies if this bug report isn't properly handled.

https://github.com/lunarbunten/enderscape/issues/21

**Comment by Juuxel** [comment]
Yeah, this appears to be an issue with Enderscape (Adorn uses some Minecraft code which Enderscape modifies to call its own code), something about it not working on dedi servers because of their config system.

I suspect this issue would still happen without Adorn, just maybe in the world and not when the game is loading.

**Comment by TeaJeep** [comment]
That seems to be the case; There's a few other reports that I overlooked since I was looking for Adorn as a keyword.  The server fails to start with or without Adorn, just with a different error. 
I'm not well versed in Github etiquette yet, but if this is resolved and not Adorn's fault, should I close the issue?  Or in this case is it better to leave it open in case someone else comes looking here from the Enderscape bug?

**Comment by Juuxel** [comment]
Ah, alright. Thanks for investigating the issue!
