### ISSUE TITLE
False release on 1.19.2 release

### ISSUE THREAD

**Issue by suerion** [Juuxel/Adorn#310]
### Adorn version

4.2.0+1.19.4

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.19

### Describe the bug

After loading the latest update for 1.19.2 i think there is an false release in it.

```
[14:46:42] [main/INFO]: Fix: add [], remove [], replace [[adorn 4.2.0+1.19.4] -> add:adorn 1 ([(-Ôê×,Ôê×)])]
[14:46:42] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Adorn' (adorn) 4.2.0+1.19.4 with any version that is compatible with:
                 - minecraft 1.19.2
Unmet dependency listing:
         - Mod 'Adorn' (adorn) 4.2.0+1.19.4 requires any version between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
```

### To reproduce

Load the latest version for 1.19.2 and start the Server

### Additional context

https://www.curseforge.com/minecraft/mc-mods/adorn/files

**Comment by Juuxel** [comment]
Fixed, thanks for the report!
