### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by he3als** [Juuxel/Adorn#346]
The latest build from the 1.20.4 branch doesn't seem to work with 1.21 unfortunately

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adorn'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalAccessError: class juuxel.adorn.AdornCommon tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (juuxel.adorn.AdornCommon and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4f7d0008)
	at juuxel.adorn.AdornCommon.id(AdornCommon.java:9)
	at juuxel.adorn.platform.fabric.RegistrarImpl.register(RegistrarImpl.kt:14)
	at juuxel.adorn.lib.AdornSounds.register(AdornSounds.java:35)
	at juuxel.adorn.lib.AdornSounds.<clinit>(AdornSounds.java:15)
	at juuxel.adorn.Adorn.onInitialize(Adorn.kt:35)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
```

**Comment by pcal43** [comment]
FWIW, I've been testing the 1.21 branch with [one tiny fix](https://github.com/pcal43/Adorn/tree/pcal/1.21), seems to work fine.

Thanks for the great mod.

**Comment by Juuxel** [comment]
Adorn 6.0.0 supports 1.21.1.

---

@pcal43 I'm not exactly sure what the issue is - the code already compiles. I guess Eclipse might have different inference rules for generics?
