### ISSUE TITLE
Crash with Adorn 1.9.1 and ExtraPieces 2.9.0

### ISSUE THREAD

**Issue by jarincodes** [Juuxel/Adorn#92]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.9.1
- Minecraft: 1.61.
- Fabric Loader: 0.9.0+build.204-1.16.1
- Fabric API: 0.16.2+build.385-1.16.1

### Describe the bug
When I try to load Minecraft with Adorn 1.9.1 and ExtraPieces 2.9.0 (the newly updated version), it crashes on start-up due to some kind of entrypoint error (crash log is below under "Additional Context").

### To Reproduce
1. Have Adorn 1.9.1 installed.
2. Have ExtraPieces 2.9.0 installed.
3. Boot Minecraft from launcher.
4. See crash/error.

### Expected behavior
To be able to boot Minecraft with no issues and be able to play the game with both mods installed as I have in the past before updating them + Minecraft itself.

### Additional context *(Optional)*
Here is the information from the crash report:

`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extrapieces'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'extrapieces' provided by 'adorn'
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:163)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:246)
	at com.shnupbups.extrapieces.ExtraPieces.onInitialize(ExtraPieces.java:91)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2160/1182100059.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: juuxel.adorn.compat.extrapieces.AdornPieces
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.java:42)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:156)
	... 15 more
Caused by: java.lang.ClassNotFoundException: juuxel.adorn.compat.extrapieces.AdornPieces
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.java:40)
	... 18 more`

**Comment by Linguardium** [comment]
https://github.com/Juuxel/Adorn/blob/ee0911883b2ef672cd85dae12fc5572f0eff0634/src/main/resources/fabric.mod.json#L36
https://github.com/Juuxel/Adorn/blob/ee0911883b2ef672cd85dae12fc5572f0eff0634/src/main/kotlin/juuxel/adorn/compat/extrapieces/AdornPieces.kt#L20

registers entrypoint to a commented out class. this causes crashes with Extra Pieces

this can be fixed with a workaround by editing the fabric.mod.json in the jar to remove the extrapieces entrypoint

**Comment by jarincodes** [comment]
Awesome! That seems to have worked. Thank you much!
