### ISSUE TITLE
Server crash with Extra Pieces compatibility, Terrestria and Traverse installed

### ISSUE THREAD

**Issue by tambry** [Juuxel/Adorn#96]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.10.0
- Minecraft: 1.16.1
- Fabric Loader: 0.9.0+build204
- Fabric API: 0.16.2+build.385
- Extra Pieces: 2.9.0
- Terrestria: 2.0.4
- Traverse: 2.2.14

### Describe the bug
Server crashes on startup if Adorn, Extra Pieces, Terrestria and Traverse are installed and Extra Pieces compatibility is enabled in Adorn.

### To Reproduce
1. Install Fabric server
2. Install [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3018319), [Adorn](https://www.curseforge.com/minecraft/mc-mods/adorn/files/3023062), [Kotlin support](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/2989695), [Terrestria](https://www.curseforge.com/minecraft/mc-mods/terrestria/files/3010731), [Traverse](https://www.curseforge.com/minecraft/mc-mods/traverse/files/3010394), [Extra Pieces](https://www.curseforge.com/minecraft/mc-mods/extra-pieces/files/3019678)
3. Start the server

`extraPieces.enabled` needs to be `true` in the config for the crash to occur. This is the case for the default config.

```
[18:28:13] [main/INFO]: Loading for game Minecraft 1.16.1
[18:28:14] [main/INFO]: [FabricLoader] Loading 61 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, parchment@1.0.2+1.15.2, fabric-keybindings-v0@0.2.0+3fa9f7c502, terrestria@2.0.4+build.50, libcd@2.4.1+1.16-pre2, fabricloader@0.9.0+build.204, artifice@0.8.1+1.16.1, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, fabric-dimensions-v1@1.0.0+a71b305302, extrapieces@2.9.0, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.2.0+e83e061c02, traverse@2.2.14+build.28, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, fabric-loot-tables-v1@1.0.0+386eb69e02, fabric@0.16.2+build.385-1.16.1, fabric-particles-v1@0.2.1+0a6f2a7002, terraform@2.1.7+build.31, fabric-networking-v0@0.1.10+e00ecb5f02, fabric-screen-handler-api-v1@1.1.0+97324d1102, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, jankson@3.0.0+j1.2.0, fabric-command-api-v1@1.0.8+5ce5339802, fabric-tool-attribute-api-v1@1.2.0+55e0cc5f02, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, fabric-renderer-indigo@0.3.4+34d6c87102, fabric-biomes-v1@0.2.7+059ea86602, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, shapes@2.0.0+build.10, libgui@2.0.1+1.16.1, fabric-language-kotlin@1.3.72+build.1, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.1+f404f3be02, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, fabric-resource-loader-v0@0.2.6+f41e209802, org_jetbrains_kotlin_kotlin-reflect@1.3.72, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-commands-v0@0.2.0+52d3083602, fabric-registry-sync-v0@0.3.8+7dba2d6c02, adorn@1.10.0+1.16.1, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, libstructure@1.3, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, fabric-object-builders-v0@0.6.1+a2d21ddd02, org_jetbrains_annotations@17.0.0
[18:28:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Raul/Desktop/Programs/Minecraft/crash/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[18:28:17] [main/WARN]: Error loading class: net/minecraft/class_5369$class_5372 (java.lang.ClassNotFoundException: net/minecraft/class_5369$class_5372)
[18:28:17] [main/WARN]: @Mixin target net.minecraft.class_5369$class_5372 was not found artifice.mixins.json:MixinExtendedResourcePackEntryInfo
[18:28:17] [main/WARN]: Error loading class: net/minecraft/class_521$class_4271 (java.lang.ClassNotFoundException: net/minecraft/class_521$class_4271)
[18:28:17] [main/WARN]: @Mixin target net.minecraft.class_521$class_4271 was not found artifice.mixins.json:MixinResourcePackEntry
[18:28:27] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[18:28:31] [main/INFO]: [Extra Pieces] Loading config
[18:28:46] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adorn'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at juuxel.adorn.Adorn.onInitialize(Adorn.java:25) ~[Adorn-1.10.0+1.16.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:block / adorn:basalt_post] at different raw IDs (4024, 4578)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$zcc000$setPre(class_2370.java:647) ~[intermediary-server.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java) ~[intermediary-server.jar:?]
	at net.minecraft.class_2348.method_10273(class_2348.java:27) ~[intermediary-server.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:69) ~[intermediary-server.jar:?]
	at net.minecraft.class_2378.method_10230(class_2378.java:359) ~[intermediary-server.jar:?]
	at juuxel.adorn.lib.RegistryHelper.register(RegistryHelper.java:21) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.lib.RegistryHelper.access$register(RegistryHelper.java:19) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:92) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.lib.RegistryHelper.registerBlock(RegistryHelper.java:36) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.lib.RegistryHelper.registerBlock$default(RegistryHelper.java:35) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.block.AdornBlocks.<clinit>(AdornBlocks.java:103) ~[Adorn-1.10.0+1.16.1.jar:?]
	at juuxel.adorn.Adorn.onInitialize(Adorn.java:25) ~[Adorn-1.10.0+1.16.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
```

**Comment by Juuxel** [comment]
Fixed in 1.10.1.
